name: tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Prepare
        run: |
          sudo apt update
          sudo apt install -y ncat wait-for-it
          git clone https://github.com/bats-core/bats-core ~/.bats
          git clone https://github.com/bats-core/bats-support ~/.bats/lib/bats-support
          git clone https://github.com/bats-core/bats-assert ~/.bats/lib/bats-assert
          git clone https://github.com/bats-core/bats-file ~/.bats/lib/bats-file
          git clone https://github.com/jasonkarns/bats-mock ~/.bats/lib/bats-mock
      - name: Run tests
        run: |
          ALLOW_CHANGING_ETC=1 ~/.bats/bin/bats tests
